baseURL = "http://blog.hashnopolis.com"
languageCode = "en-us"
title = "Hashnopolis | My Coding Blog"
publishDir = "docs"
enableEmoji = true

[params]
  themeColor = "#7679EC"
  owner = "Lek Tin"
  # Subtitle = "Hugo is Absurdly Fast!"
  # AuthorName = "Lek Tin"
  githubUsername = "lek-tin"

[permalinks]
  post = "/post/:year/:month/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"