baseURL = "http://blog.hashnopolis.com"
languageCode = "en-us"
publishDir = "docs"
enableEmoji = true
title = "Hashnopolis"
subtitle = "Blog about coding, data science and awesome technology"
copyright = "Hashnopolis"
author = "SITE AUTHOR - Lek Tin"

[params]
  themeColor = "#7679EC"
  siteName = "Hashnopolis"
  subtitle = "Blog about coding, data science and awesome technology"
  parentSite = "http://www.hashnopolis.com"
  siteDescription = "___SITE Description___"
  siteKeywords = "___keyword, keyword, keyword___"
  owner = "OWNER - Lek Tin"
  twitterProfile = ""
  githubUsername = ""
  githubProfile = "https://github.com/lek-tin"
  contributeDest = "https://github.com/lek-tin/hashnoplis-blog/tree/contribute/docs"

[permalinks]
  post = "/post/:year/:month/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"