baseURL = "http://blog.hashjelly.com"
languageCode = "en-us"
title = "HashJelly | My Coding Journal"
author = "Lek Tin"
themeColor = "#7679EC"

[params]
  themeColor = "#7679EC"
  
[permalinks]

[taxonomies]
  tag="tags"
  category="categories"
