baseURL = "http://www.hashnopolis.com"
languageCode = "en-us"
publishDir = "docs"
enableEmoji = true
title = "Hashnopolis"
subtitle = "Computer Science, Data Science and Awesome Technology"
copyright = "Hashnopolis"
author = "SITE AUTHOR - Lek Tin"

[params]
  themeColor = "#7679EC"
  siteName = "Hashnopolis"
  subtitle = "Computer Science, Data Science and Awesome Technology"
  parentSite = "http://www.hashnopolis.com"
  siteDescription = "___SITE Description___"
  siteKeywords = "___keyword, keyword, keyword___"
  owner = "OWNER - Lek Tin"
  twitterProfile = ""
  githubUsername = ""
  githubProfile = "https://github.com/lek-tin"
  contributeRepo = "https://github.com/lek-tin/hashnopolis/blob/dev/content/"
# [menu]
#   [[menu.main]]
#     name = "home"
#     url = "/"
#   [[menu.main]]
#     name = "about"
#     url = "/about/"
#   [[menu.main]]
#     name = "javascript"
#     url = "/categories/javascript"
#   [[menu.main]]
#     name = "categories"
#     url = "/categories"
#   [[menu.main]]
#     name = "tags"
#     url = "/tags"

[permalinks]
  post = "/post/:title/"
  # post = "/post/:year/:month/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"