baseURL = "http://blog.hashjelly.com"
languageCode = "en-us"
title = "HashJelly | My Coding Journal"
publishDir = "docs"
enableEmoji = true

[params]
  themeColor = "#7679EC"
  owner = "Lek Tin"
  # Subtitle = "Hugo is Absurdly Fast!"
  # AuthorName = "Lek Tin"
  # GitHubUser = "lek-tin"

[permalinks]
  # post = "/:year/:month/:title/"

[taxonomies]
  tag="tags"
  category="categories"
  owner="owners"
